/**
 * Unit tests for quark/core/uuid/uuid.h
 * Covers quark::MTUUID: isUUID, generateUUID, generateShortUUID,
 * generateUUIDWithoutHyphen.
 */

#include <gtest/gtest.h>
#include <regex>
#include <set>
#include "quark/core/uuid/uuid.h"

// ============================================================
//  isUUID
// ============================================================

TEST(MTUUIDIsUUID, ValidLowercaseUUID) {
    EXPECT_TRUE(quark::MTUUID::isUUID("550e8400-e29b-41d4-a716-446655440000"));
}

TEST(MTUUIDIsUUID, ValidVersion4UUID) {
    // Typical v4 UUID generated by the library should pass
    EXPECT_TRUE(quark::MTUUID::isUUID("f47ac10b-58cc-4372-a567-0e02b2c3d479"));
}

TEST(MTUUIDIsUUID, AllZerosUUID) {
    EXPECT_TRUE(quark::MTUUID::isUUID("00000000-0000-0000-0000-000000000000"));
}

TEST(MTUUIDIsUUID, AllHexMaxUUID) {
    EXPECT_TRUE(quark::MTUUID::isUUID("ffffffff-ffff-ffff-ffff-ffffffffffff"));
}

TEST(MTUUIDIsUUID, UppercaseReturnsFalse) {
    // Regex is strictly lowercase: [0-9a-f]
    EXPECT_FALSE(quark::MTUUID::isUUID("550E8400-E29B-41D4-A716-446655440000"));
}

TEST(MTUUIDIsUUID, MissingHyphenReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID("550e8400e29b-41d4-a716-446655440000"));
}

TEST(MTUUIDIsUUID, ExtraHyphenReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID("550e8400-e29b-41d4-a716-4466-55440000"));
}

TEST(MTUUIDIsUUID, TooShortReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID("550e8400-e29b-41d4-a716-44665544000"));
}

TEST(MTUUIDIsUUID, TooLongReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID("550e8400-e29b-41d4-a716-4466554400000"));
}

TEST(MTUUIDIsUUID, EmptyStringReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID(""));
}

TEST(MTUUIDIsUUID, RandomStringReturnsFalse) {
    EXPECT_FALSE(quark::MTUUID::isUUID("not-a-uuid-at-all"));
}

TEST(MTUUIDIsUUID, NonHexCharsReturnsFalse) {
    // 'g' is not a hex digit
    EXPECT_FALSE(quark::MTUUID::isUUID("550e8400-e29b-41d4-a716-44665544000g"));
}

// ============================================================
//  generateUUID
// ============================================================

TEST(MTUUIDGenerateUUID, LengthIs36) {
    EXPECT_EQ(quark::MTUUID::generateUUID().length(), 36u);
}

TEST(MTUUIDGenerateUUID, PassesIsUUID) {
    EXPECT_TRUE(quark::MTUUID::isUUID(quark::MTUUID::generateUUID()));
}

TEST(MTUUIDGenerateUUID, HyphensAtCorrectPositions) {
    std::string uuid = quark::MTUUID::generateUUID();
    EXPECT_EQ(uuid[8],  '-');
    EXPECT_EQ(uuid[13], '-');
    EXPECT_EQ(uuid[18], '-');
    EXPECT_EQ(uuid[23], '-');
}

TEST(MTUUIDGenerateUUID, VersionDigitIsFour) {
    // Position 14 is the version character, must be '4'
    std::string uuid = quark::MTUUID::generateUUID();
    EXPECT_EQ(uuid[14], '4');
}

TEST(MTUUIDGenerateUUID, VariantDigitIsValid) {
    // Position 19 is the variant character, must be one of '8','9','a','b'
    std::string uuid = quark::MTUUID::generateUUID();
    const std::string valid_variants = "89ab";
    EXPECT_NE(valid_variants.find(uuid[19]), std::string::npos)
        << "Variant char '" << uuid[19] << "' is not in {8,9,a,b}";
}

TEST(MTUUIDGenerateUUID, AllNonHyphenCharsAreLowercaseHex) {
    std::string uuid = quark::MTUUID::generateUUID();
    std::regex hex_char("[0-9a-f]");
    for (size_t i = 0; i < uuid.size(); ++i) {
        if (uuid[i] == '-') continue;
        std::string ch(1, uuid[i]);
        EXPECT_TRUE(std::regex_match(ch, hex_char))
            << "Non-hex character '" << uuid[i] << "' at position " << i;
    }
}

TEST(MTUUIDGenerateUUID, TwoCallsProduceDifferentValues) {
    // Probabilistically guaranteed: chance of collision is 1 in 2^122
    EXPECT_NE(quark::MTUUID::generateUUID(), quark::MTUUID::generateUUID());
}

TEST(MTUUIDGenerateUUID, MultipleCallsAreUnique) {
    std::set<std::string> uuids;
    for (int i = 0; i < 100; ++i) {
        uuids.insert(quark::MTUUID::generateUUID());
    }
    EXPECT_EQ(uuids.size(), 100u);
}

// ============================================================
//  generateShortUUID
// ============================================================

TEST(MTUUIDGenerateShortUUID, LengthIs8) {
    EXPECT_EQ(quark::MTUUID::generateShortUUID().length(), 8u);
}

TEST(MTUUIDGenerateShortUUID, AllCharsAreLowercaseHex) {
    std::string s = quark::MTUUID::generateShortUUID();
    std::regex hex_pattern("[0-9a-f]{8}");
    EXPECT_TRUE(std::regex_match(s, hex_pattern))
        << "Short UUID '" << s << "' contains non-hex characters";
}

TEST(MTUUIDGenerateShortUUID, IsFirstEightCharsOfFullUUID) {
    // Short UUID is substr(0,8) of a full UUID, so no hyphens
    std::string s = quark::MTUUID::generateShortUUID();
    EXPECT_EQ(s.find('-'), std::string::npos);
}

TEST(MTUUIDGenerateShortUUID, TwoCallsProduceDifferentValues) {
    EXPECT_NE(quark::MTUUID::generateShortUUID(),
              quark::MTUUID::generateShortUUID());
}

// ============================================================
//  generateUUIDWithoutHyphen
// ============================================================

TEST(MTUUIDGenerateUUIDWithoutHyphen, LengthIs32) {
    EXPECT_EQ(quark::MTUUID::generateUUIDWithoutHyphen().length(), 32u);
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, ContainsNoHyphen) {
    std::string s = quark::MTUUID::generateUUIDWithoutHyphen();
    EXPECT_EQ(s.find('-'), std::string::npos);
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, AllCharsAreLowercaseHex) {
    std::string s = quark::MTUUID::generateUUIDWithoutHyphen();
    std::regex hex_pattern("[0-9a-f]{32}");
    EXPECT_TRUE(std::regex_match(s, hex_pattern))
        << "UUID-without-hyphen '" << s << "' contains invalid characters";
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, VersionDigitIsFour) {
    // After removing 4 hyphens from positions 8,13,18,23:
    // original pos 14 → index 12 in the stripped string
    std::string s = quark::MTUUID::generateUUIDWithoutHyphen();
    EXPECT_EQ(s[12], '4');
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, VariantDigitIsValid) {
    // original pos 19 → index 16 in the stripped string (4 hyphens removed)
    std::string s = quark::MTUUID::generateUUIDWithoutHyphen();
    const std::string valid_variants = "89ab";
    EXPECT_NE(valid_variants.find(s[16]), std::string::npos)
        << "Variant char '" << s[16] << "' is not in {8,9,a,b}";
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, MatchesFullUUIDAfterReinsertingHyphens) {
    std::string s = quark::MTUUID::generateUUIDWithoutHyphen();
    // Re-insert hyphens to reconstruct canonical form and validate
    std::string canonical =
        s.substr(0, 8)  + "-" +
        s.substr(8, 4)  + "-" +
        s.substr(12, 4) + "-" +
        s.substr(16, 4) + "-" +
        s.substr(20, 12);
    EXPECT_TRUE(quark::MTUUID::isUUID(canonical))
        << "Reconstructed UUID '" << canonical << "' failed isUUID check";
}

TEST(MTUUIDGenerateUUIDWithoutHyphen, TwoCallsProduceDifferentValues) {
    EXPECT_NE(quark::MTUUID::generateUUIDWithoutHyphen(),
              quark::MTUUID::generateUUIDWithoutHyphen());
}

